package io.spring.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/*
 * to generate this class, run:
 * $JAVA_HOME/bin/wsimport -keep http://localhost:9999/ws/hello?wsdl
 */
/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebService(name = "SOAP", targetNamespace = "http://soap.spring.io/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SOAP
{

    /**
     * 
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getSOAPAsString(
            @WebParam(name = "arg0", partName = "arg0") String arg0);

}
